-- 03_insert_users_and_ratings.sql
-- GENERATED by R/build_database.R from data/survey_responses.csv.
-- Do not edit by hand; edit the CSV and re-run the script.

INSERT INTO users (user_id, name) VALUES
  (1, 'Friend 1'),
  (2, 'Friend 2'),
  (3, 'Friend 3'),
  (4, 'Friend 4'),
  (5, 'Friend 5'),
  (6, 'Friend 6');

INSERT INTO ratings (user_id, movie_id, rating) VALUES
  (1, 1, 5),
  (1, 2, 5),
  (1, 3, 5),
  (1, 4, 3),
  (1, 5, 4),
  (1, 6, 5),
  (2, 1, 5),
  (2, 2, 5),
  (2, 3, 5),
  (2, 4, 3),
  (2, 5, 4),
  (2, 6, 5),
  (3, 1, 5),
  (3, 2, 5),
  (3, 3, 5),
  (3, 4, 3),
  (3, 5, 4),
  (3, 6, 5),
  (4, 1, 5),
  (4, 2, 5),
  (4, 3, 5),
  (4, 4, 3),
  (4, 5, 4),
  (4, 6, 5),
  (5, 1, 4),
  (5, 2, 5),
  (5, 3, 5),
  (5, 4, 3),
  (5, 5, 5),
  (5, 6, 5),
  (6, 1, 5),
  (6, 2, 4),
  (6, 3, 5),
  (6, 4, 3),
  (6, 5, 5),
  (6, 6, 5);
