# build_database.R
# Builds movie_ratings.sqlite from the SQL scripts and the survey responses.
#
# Run from the Week2 folder:
#   Rscript R/build_database.R
#
# Steps
#   1. Run sql/01_create_tables.sql  (CREATE TABLE)
#   2. Run sql/02_insert_movies.sql  (INSERT the six movies)
#   3. Read data/survey_responses.csv, validate it, and write the
#      users + ratings INSERT statements to sql/03_insert_users_and_ratings.sql
#   4. Run that generated file, so every row in the database has SQL behind it
#
# SQLite is a local file with no server and no password, so there are no
# credentials anywhere in this project.

suppressPackageStartupMessages({
  library(DBI)
  library(RSQLite)
  library(readr)
  library(dplyr)
  library(tidyr)
})

survey_path <- "data/survey_responses.csv"
db_path     <- "movie_ratings.sqlite"
ratings_sql <- "sql/03_insert_users_and_ratings.sql"

# RSQLite runs one statement per dbExecute() call, so split each script on ";".
run_sql_file <- function(con, path) {
  sql <- paste(readLines(path, warn = FALSE), collapse = "\n")
  sql <- gsub("--[^\n]*", "", sql)                 # drop comments
  statements <- trimws(strsplit(sql, ";")[[1]])
  for (stmt in statements[nzchar(statements)]) dbExecute(con, stmt)
}

sql_quote <- function(x) paste0("'", gsub("'", "''", x), "'")

# --- 1-2. Create tables and insert movies ----------------------------------
if (file.exists(db_path)) file.remove(db_path)
con <- dbConnect(SQLite(), db_path)
on.exit(dbDisconnect(con), add = TRUE)

run_sql_file(con, "sql/01_create_tables.sql")
run_sql_file(con, "sql/02_insert_movies.sql")
movies <- dbGetQuery(con, "SELECT movie_id, title FROM movies")

# --- 3. Read and validate the survey ---------------------------------------
# Blank cells mean "has not seen this movie"; they are read as NA.
survey <- read_csv(survey_path, col_types = cols(.default = col_character()),
                   na = c("", "NA"), trim_ws = TRUE)

unknown_titles <- setdiff(names(survey)[-1], movies$title)
if (length(unknown_titles) > 0) {
  stop("Survey columns not found in the movies table: ",
       paste(unknown_titles, collapse = ", "))
}
if (nrow(survey) == 0) stop("No responses in ", survey_path, " yet.")
if (anyNA(survey$respondent) || anyDuplicated(survey$respondent)) {
  stop("Every respondent needs a unique, non-blank name.")
}

ratings_long <- survey |>
  pivot_longer(-respondent, names_to = "title", values_to = "rating") |>
  filter(!is.na(rating))                           # unseen = no row at all

bad <- ratings_long |> filter(!rating %in% as.character(1:5))
if (nrow(bad) > 0) {
  print(bad)
  stop("Ratings must be whole numbers from 1 to 5 (or blank if unseen).")
}

users <- tibble(user_id = seq_len(nrow(survey)), name = survey$respondent)

ratings_long <- ratings_long |>
  inner_join(users,  by = c("respondent" = "name")) |>
  inner_join(movies, by = "title") |>
  mutate(rating = as.integer(rating))

# --- 4. Write the INSERT statements to a .sql file, then run it ------------
insert_lines <- c(
  "-- 03_insert_users_and_ratings.sql",
  "-- GENERATED by R/build_database.R from data/survey_responses.csv.",
  "-- Do not edit by hand; edit the CSV and re-run the script.",
  "",
  "INSERT INTO users (user_id, name) VALUES",
  paste0("  (", users$user_id, ", ", sql_quote(users$name), ")",
         c(rep(",", nrow(users) - 1), ";")),
  "",
  "INSERT INTO ratings (user_id, movie_id, rating) VALUES",
  paste0("  (", ratings_long$user_id, ", ", ratings_long$movie_id, ", ",
         ratings_long$rating, ")",
         c(rep(",", nrow(ratings_long) - 1), ";"))
)
writeLines(insert_lines, ratings_sql)
run_sql_file(con, ratings_sql)

# --- Summary ---------------------------------------------------------------
n_possible <- nrow(users) * nrow(movies)
cat(sprintf("Built %s: %d people, %d movies, %d ratings, %d missing (%.0f%%)\n",
            db_path, nrow(users), nrow(movies), nrow(ratings_long),
            n_possible - nrow(ratings_long),
            100 * (n_possible - nrow(ratings_long)) / n_possible))

if (nrow(users) < 5) {
  message("Note: the assignment asks you to survey at least five people.")
}
